"""Tests for quarq/report/ — charts, renderer, and narrative."""

from __future__ import annotations

from datetime import date
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import pytest

from quarq.report.charts import (
    correlation_heatmap,
    cumulative_returns_line,
    drawdown_area,
    rolling_sharpe,
    weight_treemap,
)
from quarq.report.renderer import render_html


def _make_returns(n: int = 60, seed: int = 0) -> pd.Series:
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2024-01-02", periods=n, freq="B")
    return pd.Series(rng.normal(0.001, 0.01, n), index=idx)


def _make_returns_df(tickers: list[str] = None, n: int = 60) -> pd.DataFrame:
    if tickers is None:
        tickers = ["MC.PA", "AIR.PA", "SAN.PA"]
    rng = np.random.default_rng(42)
    idx = pd.date_range("2024-01-02", periods=n, freq="B")
    data = {t: rng.normal(0.001, 0.01, n) for t in tickers}
    return pd.DataFrame(data, index=idx)


def _make_metrics() -> SimpleNamespace:
    return SimpleNamespace(
        cagr=0.12,
        sharpe_ratio=1.2,
        max_drawdown=-0.15,
        var_95=-0.02,
        beta=0.95,
        alpha=0.01,
        volatility=0.18,
    )


def test_correlation_heatmap_returns_figure() -> None:
    """correlation_heatmap returns a go.Figure with a Heatmap trace."""
    returns_df = _make_returns_df()
    fig = correlation_heatmap(returns_df)
    assert isinstance(fig, go.Figure)
    assert len(fig.data) == 1
    assert isinstance(fig.data[0], go.Heatmap)


def test_weight_treemap_returns_figure() -> None:
    """weight_treemap returns a go.Figure with a Treemap trace."""
    weights = {"MC.PA": 0.40, "AIR.PA": 0.35, "SAN.PA": 0.25}
    sleeve_map = {"MC.PA": "Growth", "AIR.PA": "Growth", "SAN.PA": "Defensive"}
    fig = weight_treemap(weights, sleeve_map)
    assert isinstance(fig, go.Figure)
    assert len(fig.data) == 1
    assert isinstance(fig.data[0], go.Treemap)


def test_cumulative_returns_returns_figure() -> None:
    """cumulative_returns_line returns a go.Figure with two Scatter traces."""
    port = _make_returns(60, seed=1)
    bench = _make_returns(60, seed=2)
    fig = cumulative_returns_line(port, bench, label="My Portfolio")
    assert isinstance(fig, go.Figure)
    assert len(fig.data) == 2
    assert all(isinstance(t, go.Scatter) for t in fig.data)


def test_drawdown_area_returns_figure() -> None:
    """drawdown_area returns a go.Figure with a filled Scatter trace."""
    returns = _make_returns(60)
    fig = drawdown_area(returns)
    assert isinstance(fig, go.Figure)
    assert len(fig.data) == 1
    assert isinstance(fig.data[0], go.Scatter)
    assert fig.data[0].fill == "tozeroy"


def test_rolling_sharpe_returns_figure() -> None:
    """rolling_sharpe returns a go.Figure with a Scatter trace."""
    returns = _make_returns(120)
    fig = rolling_sharpe(returns, rfr=0.03, window=20)
    assert isinstance(fig, go.Figure)
    assert len(fig.data) == 1
    assert isinstance(fig.data[0], go.Scatter)


def test_render_html_contains_kpis() -> None:
    """render_html output contains portfolio name and all KPI labels."""
    port = _make_returns(60)
    bench = _make_returns(60, seed=1)
    returns_df = _make_returns_df()

    figures = {
        "cumulative_returns": cumulative_returns_line(port, bench),
        "drawdown": drawdown_area(port),
        "rolling_sharpe": rolling_sharpe(port, rfr=0.03, window=20),
        "correlation_heatmap": correlation_heatmap(returns_df),
        "weight_treemap": weight_treemap(
            {"MC.PA": 0.5, "SAN.PA": 0.5},
            {"MC.PA": "Equity", "SAN.PA": "Equity"},
        ),
    }

    html = render_html(
        portfolio_name="Test Portfolio",
        metrics=_make_metrics(),
        figures=figures,
        narrative="This is a test narrative.",
        benchmark="^FCHI",
        period_start="2024-01-01",
        period_end="2024-12-31",
        currency="EUR",
        report_date="2024-12-31",
    )

    assert "Test Portfolio" in html
    assert "CAGR" in html
    assert "Sharpe" in html
    assert "Max Drawdown" in html
    assert "VaR" in html
    assert "This is a test narrative." in html
    assert "Generated by quarq" in html


def test_generate_narrative_returns_string() -> None:
    """generate_narrative returns a non-empty string when LLM succeeds."""
    from quarq.api.metrics import generate_narrative
    from quarq.api.models import MetricsResponse

    metrics = MetricsResponse(
        tickers=["MC.PA"],
        weights=[1.0],
        start=date(2024, 1, 1),
        end=date(2024, 12, 31),
        cagr=0.12,
        sharpe_ratio=1.2,
        max_drawdown=-0.15,
        var_95=-0.02,
        beta=0.9,
        alpha=0.01,
        volatility=0.18,
    )

    mock_llm = MagicMock()
    mock_llm.generate.return_value = "Strong risk-adjusted performance driven by Growth sleeve."

    with patch("quarq.llm.lmstudio.get_llm", return_value=mock_llm):
        cfg = MagicMock()
        result = generate_narrative(metrics, cfg)

    assert isinstance(result, str)
    assert len(result) > 0


def test_generate_narrative_empty_on_failure() -> None:
    """generate_narrative returns empty string when LLM raises."""
    from quarq.api.metrics import generate_narrative
    from quarq.api.models import MetricsResponse

    metrics = MetricsResponse(
        tickers=["MC.PA"],
        weights=[1.0],
        start=date(2024, 1, 1),
        end=date(2024, 12, 31),
        cagr=0.12,
        sharpe_ratio=1.2,
        max_drawdown=-0.15,
        var_95=-0.02,
        beta=0.9,
        alpha=0.01,
        volatility=0.18,
    )

    with patch("quarq.llm.lmstudio.get_llm", side_effect=RuntimeError("LM Studio unavailable")):
        cfg = MagicMock()
        result = generate_narrative(metrics, cfg)

    assert result == ""
